baseURL = "https://lipukule.org/"
languageCode = "tpo"
title = "lipu kule"
theme = "lt"
paginate = 6
DefaultContentLanguage = "tpo"

[markup.goldmark.renderer]
    unsafe = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    lipu = "/lipu/:year/:month/:day/:slug/"
    mi = "/mi/:slug/"

[params]
    description = "lipu sona pi toki pona."
	
[taxonomies]
	category = "categories"
	color = "color"
	author = "author"

[languages]
    [languages.tpo]
    contentDir = "content/tpo"
    languageName = "toki pona"
    weight = 1